# This is a workflow, consisting of jobs that only need to be run,
# once `*nix`, or `flake.lock` files change
name: nix-develop

on:
  push:
    branches:
      - master
    paths:
      - '**.nix'
      - 'flake.lock'
  pull_request:
    branches:
      - master
    paths:
      - '**.nix'
      - 'flake.lock'

  develop:
    runs-on: ubuntu-latest
    name: "nix develop"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v19
      - run: nix develop --profile devShell
      - run: nix develop .#fmtShell --profile fmtShell
